# Generated by Django 2.2 on 2022-06-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='chat_room',
            field=models.CharField(default='chat_general', max_length=120),
        ),
    ]
